### ISSUE TITLE
"test my browser" service

### ISSUE THREAD

**Issue by arthuredelstein** [privacytests/privacytests.org#53]

**Comment by mutageneral** [comment]
If the current testing project (in /testing/) can be made cross-platform and have a more intuitive guide on how to use, then I don't think this would be necessarily needed.

**Comment by IronMaltese** [comment]
I know that https://privacytests.org/me.html tests the user's web browser, will this be implemented into the main site?

**Comment by arthuredelstein** [comment]
@IronMaltese yes. The feature is still in a pre-alpha stage, so I haven't added a link to the main site yet.

**Comment by mutageneral** [comment]
got this bug on brave trying the privacy test:
```
TypeError: Cannot read properties of undefined (reading 'description')
    at resultsSection (/home/arthur/privacytests.org/scripts/render.js:272:57)
    at resultsToTable (/home/arthur/privacytests.org/scripts/render.js:306:26)
    at content (/home/arthur/privacytests.org/scripts/render.js:328:29)
    at contentPage (/home/arthur/privacytests.org/scripts/render.js:390:14)
    at /home/arthur/privacytests.org/live/results.js:229:16
    at Layer.handle [as handle_request] (/home/arthur/privacytests.org/live/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/arthur/privacytests.org/live/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/arthur/privacytests.org/live/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/arthur/privacytests.org/live/node_modules/express/lib/router/layer.js:95:5)
    at /home/arthur/privacytests.org/live/node_modules/express/lib/router/index.js:281:22
```

**Comment by arthuredelstein** [comment]
Hi @mutageneral -- I'm not seeing this error. Would you mind trying again?

**Comment by mutageneral** [comment]
Still the same problem. It does not happen in private mode, so it might be one of my add-ons.
